"""Generate current native/SVG brand assets from the approved palette and geometry.

Run with Python 3. Use --check to verify generated files without writing them.
Historical exploration assets are never modified.
"""

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
ANDROID = "app/src/main/res"
PALETTE = json.loads((ROOT / "design/tokens/tokens.json").read_text(encoding="utf-8"))["brand"]
GEOMETRY = json.loads((ROOT / "design/brand/lianye/refined-01/geometry.json").read_text(encoding="utf-8"))


def paths(variant):
    return [(item["role"], " ".join(" ".join(map(str, segment)) for segment in item["segments"]))
            for item in GEOMETRY[variant]["paths"]]


def vector(variant, corners, page, adaptive=True):
    size = 108 if adaptive else 100
    dimension = 108 if adaptive else 42
    scale = GEOMETRY["adaptive"]["scale"]
    group = (f'android:translateX="{54 - 50 * scale:g}" android:translateY="{54 - 53 * scale:g}" '
             f'android:scaleX="{scale}" android:scaleY="{scale}"') if adaptive else 'android:translateY="-3"'
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- Generated by tool/sync_brand_assets.py. -->',
             f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{dimension}dp" '
             f'android:height="{dimension}dp" android:viewportWidth="{size}" android:viewportHeight="{size}">',
             f'    <group {group}>']
    for role, path in paths(variant):
        color = page if role == "page" else corners
        lines.append('        <path android:fillColor="@android:color/transparent" '
                     f'android:strokeColor="{color}" android:strokeWidth="{GEOMETRY[variant]["stroke"]}" '
                     f'android:strokeLineJoin="round" android:pathData="{path}" />')
    return "\n".join(lines + ['    </group>', '</vector>', ''])


def svg(variant, corners, page, adaptive=True, background=None):
    size = 108 if adaptive else 100
    scale = GEOMETRY["adaptive"]["scale"]
    transform = f'translate(54 54) scale({scale}) translate(-50 -53)' if adaptive else 'translate(0 -3)'
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
             f'viewBox="0 0 {size} {size}" role="img" aria-label="连页：超过一屏的长图">',
             '<!-- Generated by tool/sync_brand_assets.py. -->']
    if background:
        lines.append(f'<rect width="{size}" height="{size}" fill="{background}"/>')
    lines.append(f'<g transform="{transform}">')
    for role, path in paths(variant):
        color = page if role == "page" else corners
        lines.append(f'<path data-role="{role}" d="{path}" fill="none" stroke="{color}" '
                     f'stroke-width="{GEOMETRY[variant]["stroke"]}" stroke-linecap="butt" stroke-linejoin="round"/>')
    return "\n".join(lines + ['</g>', '</svg>', ''])


def generated_files():
    for value in PALETTE.values():
        if not re.fullmatch(r"#[0-9A-F]{6}", value):
            raise ValueError("Expected an opaque uppercase RGB brand color")
    names = {"Paper": "paper", "Ink": "ink", "Accent": "accent",
             "DarkBackground": "darkBackground", "DarkAccent": "darkAccent"}
    kotlin = ["package org.lianye.ui.common.theme", "", "import androidx.compose.ui.graphics.Color", "",
              "// Generated by tool/sync_brand_assets.py from design/tokens/tokens.json.",
              "internal object BrandPalette {"]
    kotlin += [f"    val {name} = Color(0xFF{PALETTE[key][1:]})" for name, key in names.items()]
    kotlin += ["}", ""]
    colors = ['<?xml version="1.0" encoding="utf-8"?>', '<resources>',
              '    <!-- Generated by tool/sync_brand_assets.py. Fixed colors also serve the launcher. -->']
    resources = {"brand_paper": "paper", "brand_ink": "ink", "brand_accent": "accent",
                 "brand_dark_background": "darkBackground", "brand_dark_accent": "darkAccent"}
    colors += [f'    <color name="{name}">{PALETTE[key]}</color>' for name, key in resources.items()]
    colors += ['    <color name="brand_background">@color/brand_paper</color>',
               '    <color name="brand_mark_foreground">@color/brand_ink</color>',
               '    <color name="brand_mark_accent">@color/brand_accent</color>', '</resources>', '']
    night = ['<?xml version="1.0" encoding="utf-8"?>', '<resources>',
             '    <!-- Generated by tool/sync_brand_assets.py. -->',
             '    <color name="brand_background">@color/brand_dark_background</color>',
             '    <color name="brand_mark_foreground">@color/brand_paper</color>',
             '    <color name="brand_mark_accent">@color/brand_dark_accent</color>', '</resources>', '']
    background = ['<?xml version="1.0" encoding="utf-8"?>',
                  '<!-- Generated by tool/sync_brand_assets.py. -->',
                  '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" '
                  'android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">',
                  '    <path android:fillColor="@color/brand_paper" android:pathData="M0,0 H108 V108 H0 Z"/>',
                  '</vector>', '']
    paper, ink, accent = (PALETTE[key] for key in ("paper", "ink", "accent"))
    return {
        "app/src/main/java/org/lianye/ui/common/theme/BrandPalette.kt": "\n".join(kotlin),
        f"{ANDROID}/values/brand_colors.xml": "\n".join(colors),
        f"{ANDROID}/values-night/brand_colors.xml": "\n".join(night),
        f"{ANDROID}/drawable/ic_launcher_background.xml": "\n".join(background),
        f"{ANDROID}/drawable/ic_launcher_foreground.xml": vector("optical", "@color/brand_ink", "@color/brand_accent"),
        f"{ANDROID}/drawable/ic_launcher_monochrome.xml": vector("optical", "@android:color/white", "@android:color/white"),
        f"{ANDROID}/drawable/ic_main_header_shuttle.xml": vector("primary", "@color/brand_mark_foreground", "@color/brand_mark_accent", False),
        f"{ANDROID}/drawable/ic_splash_mark.xml": vector("optical", "@color/brand_mark_foreground", "@color/brand_mark_accent"),
        "design/brand/logo_foreground.svg": svg("optical", ink, accent),
        "design/brand/logo_background.svg": f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><rect width="108" height="108" fill="{paper}"/></svg>\n',
        "design/brand/logo_master.svg": svg("optical", ink, accent, background=paper),
        "design/brand/logo_monochrome.svg": svg("optical", ink, ink),
        "design/brand/logo_symbol.svg": svg("primary", ink, accent, False),
        "design/brand/logo_symbol_dark.svg": svg("primary", paper, PALETTE["darkAccent"], False),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = generated_files()
    different = []
    for relative, content in files.items():
        target = ROOT / relative
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                different.append(relative)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("w", encoding="utf-8", newline="\n") as output:
                output.write(content)
    if different:
        print("Brand assets differ: " + ", ".join(different))
        return 1
    print(f'{"Checked" if args.check else "Generated"} {len(files)} brand assets.')
    return 0


if __name__ == "__main__":
    sys.exit(main())
