import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const runtime='C:/Users/wgx/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {chromium}=createRequire(runtime+'package.json')('playwright');
const dir=new URL('./',import.meta.url),review=new URL('review/',dir);
const browser=await chromium.launch({headless:true,executablePath:'C:/Users/wgx/.cache/puppeteer/chrome/win64-151.0.7922.71/chrome-win64/chrome.exe'});
const context=await browser.newContext({viewport:{width:736,height:950}});
await context.addInitScript({path:runtime+'lucide/dist/umd/lucide.min.js'});
await context.addInitScript(()=>{window.openai={widgetState:null,setWidgetState:async v=>{window.openai.widgetState=v;setTimeout(()=>window.dispatchEvent(new CustomEvent('openai:set_globals',{detail:{globals:{widgetState:v}}})),25);}};});
const page=await context.newPage(),checks=[],errors=[],layouts=[];page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));
const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
const action=a=>page.locator('#ly-interaction-prototype [data-action="'+a+'"]:visible');
const click=async a=>action(a).first().click();
const scenario=async v=>page.locator('#ly-scenario').selectOption(v);
const state=()=>page.evaluate(()=>window.openai.widgetState.privateContent.experience);
const shot=async n=>page.locator('.ly-phone').screenshot({path:fileURLToPath(new URL(n+'.png',review))});
const scroll=async y=>{await page.locator('.ly-target-scroll').evaluate((e,y)=>{e.scrollTop=y;},y);await page.waitForTimeout(260);};
const phase=async p=>page.waitForFunction(p=>window.openai.widgetState?.privateContent.experience.manualPhase===p,p);
const prepare=async(v='manual')=>{await scenario(v);await click('start');await click('projection-allow');await click('open-browser');};
const begin=async(v='manual')=>{await prepare(v);await click('capture');await phase('recording');};
const end=async()=>{await click('stop');await page.getByRole('heading',{name:'长图',exact:true}).waitFor();};
const inside=async()=>page.locator('.ly-phone').evaluate(phone=>{
  const screen=phone.querySelector('#ly-screen').getBoundingClientRect();
  return [...phone.querySelectorAll('.ly-manual-float,.ly-float-tip,.ly-swipe-guide,.ly-swipe-caption,.ly-guide-close')].filter(e=>e.getClientRects().length).every(e=>{const r=e.getBoundingClientRect();return r.left>=screen.left&&r.right<=screen.right&&r.top>=screen.top&&r.bottom<=screen.bottom;});
});
try{
  await page.goto(pathToFileURL(fileURLToPath(new URL('../../../../build/lianye-prototype/preview.html',dir))).href);
  check('默认展示本轮手动情境',await action('start').textContent().then(t=>t.includes('手动长截图')));
  await scenario('first');await click('start');await shot('manual-01-entry');
  check('首次自动准备保留手动入口',await action('manual').count()===1);
  await click('manual');await shot('manual-02-consent');
  check('选择手动只请求本次屏幕捕获',await action('projection-allow').count()===1&&!(await state()).permission);
  await click('projection-deny');
  check('取消授权没有服务或虚构草稿',!(await state()).projection&&!(await state()).permission&&!(await state()).draft);
  await scenario('first');await click('start');await click('to-system');await page.locator('#ly-system-enable').click();await click('system-deny');
  check('真实拒绝无障碍仍有手动入口',await action('manual').count()===1);
  await click('manual');await click('projection-allow');await shot('manual-03-desktop');
  check('授权完成只进入准备，进度仍为零',(await state()).frames===0&&(await state()).manualPhase==='idle'&&!(await state()).permission);
  check('桌面提示明确打开页面并点击开始',await page.locator('.ly-desktop-hint').textContent().then(t=>t.includes('打开')&&t.includes('开始')));
  await click('manual-cancel');
  check('取消准备释放本次授权',!(await state()).projection&&(await state()).screen==='home'&&!(await state()).draft);
  await prepare();await shot('manual-10-ready');await page.waitForTimeout(600);
  check('打开页面与等待不产生首屏',(await state()).frames===0&&(await state()).screen==='target');
  check('开始前明确提示找到起点',await page.locator('.ly-float-tip.prepare').textContent().then(t=>t.includes('起点')&&t.includes('开始')));
  await scroll(310);check('开始前浏览不被拼入长图',(await state()).frames===0);
  await click('capture');check('点击开始后等待有效首屏，不虚构计数',(await state()).frames===0&&(await state()).manualPhase==='taking');
  await phase('recording');check('从实际开始位置记录首屏',(await state()).frames===1&&(await state()).manualOrigin===310);
  await end();check('任意起点且只有一屏也可正常结束',(await state()).draft.frames===1&&!(await state()).draft.interrupted&&(await state()).draft.sourceOffset===310);
  await prepare();await page.evaluate(()=>{document.querySelector('[data-action="capture"]').click();document.querySelector('[data-action="stop"]').click();});
  check('首屏回调前结束只能等待，不得自行确认画面',(await state()).frames===0&&(await state()).manualPhase==='taking'&&(await state()).manualEnding);
  await page.getByRole('heading',{name:'长图',exact:true}).waitFor();check('等待原首屏回调后才生成有效结果',(await state()).draft.frames===1);
  await begin();await shot('manual-04-capturing');
  check('首屏成功后可见真实成功状态和结束',await action('stop').textContent().then(t=>t.includes('已截 1 屏')&&t.includes('结束')));
  check('首次教学明确起点终点和停顿',await page.locator('.ly-swipe-guide:not(.compact)').textContent().then(t=>t.includes('从这里')&&t.includes('向上滑')&&t.includes('到这里')&&t.includes('松手稍停')));
  check('参考路线向上且距离约半个内容区',await page.locator('.ly-swipe-guide').evaluate(e=>{const start=e.querySelector('.ly-swipe-dot.start').getBoundingClientRect(),end=e.querySelector('.ly-swipe-dot.end').getBoundingClientRect();const d=(start.top-end.top)/e.clientHeight;return start.top>end.top&&d>.4&&d<.5;}));
  check('指导主体不拦截滑动，关闭按钮有足够触控面积',await page.locator('.ly-swipe-guide').evaluate(e=>{const b=e.querySelector('button'),r=b.getBoundingClientRect();return getComputedStyle(e).pointerEvents==='none'&&getComputedStyle(b).pointerEvents==='auto'&&r.width>=44&&r.height>=44;}));
  await page.waitForTimeout(650);check('正常停留不自行滑动或结束',(await state()).frames===1&&(await state()).screen==='capturing'&&await page.locator('.ly-target-scroll').evaluate(e=>e.scrollTop===0));
  await page.locator('.ly-target-scroll').evaluate(e=>window.manualScrollNode=e);await page.locator('.ly-target-scroll').hover();await page.mouse.wheel(0,310);await page.waitForTimeout(300);
  check('实际滚轮稳定后新增有效内容',(await state()).frames===2);
  check('更新反馈不重建目标浏览页面',await page.locator('.ly-target-scroll').evaluate(e=>e===window.manualScrollNode));
  check('首次接上新内容只收起文字，保留简化路线',(await state()).manualHintSeen&&await page.locator('.ly-swipe-guide.compact').isVisible()&&!await page.locator('.ly-swipe-caption').first().isVisible()&&await page.locator('.ly-swipe-arrow').isVisible());
  await shot('manual-11-progress');await scroll(100);await scroll(310);
  check('回滑和重复位置不虚增进度也不重新弹出文字',(await state()).frames===2&&await page.locator('.ly-swipe-guide.compact').isVisible());
  await page.evaluate(()=>{const el=document.querySelector('.ly-target-scroll');el.scrollTop=620;el.dispatchEvent(new Event('scroll'));document.querySelector('[data-action="stop"]').click();});
  await page.getByRole('heading',{name:'长图',exact:true}).waitFor();
  check('滑完立刻结束仍收尾待处理内容',(await state()).draft.frames===3);
  check('主动结束释放授权且不启用无障碍',!(await state()).projection&&!(await state()).permission&&await page.locator('.ly-projection-indicator').count()===0);
  check('结束时参考路线和关闭提示都被清除',await page.locator('.ly-swipe-guide').count()===0&&await action('dismiss-swipe-guide').count()===0);
  check('共同结果只有裁剪保存分享',await action('crop').count()===1&&await action('save').count()===1&&await action('share').count()===1);
  await shot('manual-05-result');await click('draft-home');await click('new');await click('discard-new');await click('projection-allow');await click('open-browser');await click('capture');await phase('recording');
  check('下一轮重新授权，已学过时直接保留简化路线',(await state()).manualHintSeen&&await page.locator('.ly-swipe-guide.compact').isVisible());
  await scroll(310);await scroll(620);check('连续接图后路线仍保留，文字不重现',(await state()).frames===3&&await page.locator('.ly-swipe-guide.compact').isVisible());await shot('manual-23-guide-retained');
  await action('dismiss-swipe-guide').focus();await page.keyboard.press('Enter');
  check('主动关闭只隐藏指导，截图继续且焦点回到结束',(await state()).manualGuideDismissed&&(await state()).projection&&(await state()).manualPhase==='recording'&&await page.locator('.ly-swipe-guide').count()===0&&await action('stop').evaluate(e=>e===document.activeElement));
  await scroll(930);check('关闭后继续接图不会重新显示指导',(await state()).frames===4&&await page.locator('.ly-swipe-guide').count()===0);await shot('manual-24-guide-dismissed');await end();
  await click('draft-home');await click('new');await click('discard-new');await click('projection-allow');await click('open-browser');await click('capture');await phase('recording');
  check('主动关闭仅本次有效，新会话恢复简化路线',!(await state()).manualGuideDismissed&&await page.locator('.ly-swipe-guide.compact').isVisible());
  await end();await click('draft-home');await click('settings');await click('help');await shot('manual-06-help');
  check('手动帮助明确开始和结束',await page.locator('.ly-steps').textContent().then(t=>t.includes('本次屏幕捕获')&&t.includes('开始')&&t.includes('自己滑动')&&t.includes('结束')));
  check('自动设置帮助仍默认折叠',await page.locator('.ly-auto-help').count()===1&&!await page.locator('.ly-auto-help').evaluate(e=>e.open));
  for(const vendor of ['xiaomi','oppo','vivo','huawei','samsung','aosp']){await page.locator('#ly-vendor').selectOption(vendor);check(vendor+' 厂商自动设置路径仍保留',await page.locator('.ly-auto-help .ly-device-path').count()===1);}
  await page.locator('.ly-auto-help>summary').click();await click('help-system');await page.locator('#ly-system-enable').click();await click('system-allow');await click('system-back');
  check('主动启用自动服务后恢复自动路径',(await state()).mode==='auto'&&(await state()).permission);
  await begin();await scroll(310);await scroll(980);await shot('manual-12-gap-live');
  check('缺口出现即明确反馈并冻结数字',(await state()).manualGap&&(await state()).frames===2&&await page.locator('.ly-float-tip.error').textContent().then(t=>t.includes('未能接上')&&t.includes('结束')));
  check('接续失败后退出路线，错误说明优先',await page.locator('.ly-swipe-guide').count()===0);
  await scroll(1000);check('失败后不继续制造完整长图假象',(await state()).frames===2);
  await end();await shot('manual-07-gap');
  check('结果保留可靠前段且不随意归责滑动过快',await page.locator('.ly-result-notice').textContent().then(t=>t.includes('未能接上')&&t.includes('2 屏')&&!t.includes('过快')));
  await prepare('manual-first-failure');await click('capture');await phase('failed');await shot('manual-13-first-failure');
  check('首屏失败可见并可重试，进度为零',await page.locator('.ly-float-tip.error').textContent().then(t=>t.includes('未截到画面'))&&(await state()).frames===0&&await action('capture').textContent().then(t=>t.includes('重试')));
  await click('capture');await phase('recording');check('就地重试成功，无需再请求本次授权',(await state()).frames===1&&(await state()).projection);await end();
  await prepare('manual-first-failure');await click('capture');await phase('failed');await click('home');
  check('没有有效画面结束不伪造草稿',(await state()).screen==='home'&&!(await state()).draft&&await page.locator('.ly-denied').textContent().then(t=>t.includes('还未截到画面')));
  await prepare('manual-notification');check('通知兜底不用悬浮或无障碍',await page.locator('.ly-manual-float').count()===0&&!(await state()).permission);
  check('通知入口模拟下拉状态栏，不改变屏捕标记的系统含义',await action('notifications-open').getAttribute('aria-label').then(t=>t.includes('下拉'))&&await action('notifications-open').locator('.ly-projection-indicator').count()===0);
  await click('notifications-open');await shot('manual-14-notification-ready');
  check('通知面板完全覆盖目标页面，不漏出底部内容',await page.locator('.ly-notification-shade').evaluate(e=>e.getBoundingClientRect().bottom>=document.querySelector('#ly-screen').getBoundingClientRect().bottom));
  check('通知栏在开始前说明滑动与结束',await page.locator('.ly-capture-notification').textContent().then(t=>t.includes('半屏')&&t.includes('结束')&&t.includes('开始')));
  await click('capture');await phase('recording');check('首屏成功通知反馈可见',await page.locator('.ly-system-toast').textContent().then(t=>t.includes('已截 1 屏')));
  check('通知模式不增加跨应用路线或悬浮授权',await page.locator('.ly-swipe-guide').count()===0&&!(await state()).overlayAllowed);
  await scroll(310);await click('notifications-open');await shot('manual-15-notification-progress');
  check('通知栏显示有效进度和结束',await page.locator('.ly-capture-notification').textContent().then(t=>t.includes('已截 2 屏')&&t.includes('结束')));
  await end();check('通知结束同样释放授权并进入预览',(await state()).draft.frames===2&&!(await state()).projection);
  await scenario('manual-blocked');await click('start');await click('projection-allow');await shot('manual-16-control-blocked');
  check('双入口不可用时留在准备，不将用户送出',(await state()).sheet==='control'&&(await state()).frames===0&&await action('open-browser').count()===0);
  check('需要的控制能力只在阻塞分支解释',await page.getByRole('dialog').textContent().then(t=>t.includes('悬浮球或通知')));
  await click('enable-overlay');check('悬浮授权使用模拟系统设置开关',await page.locator('#ly-manual-overlay').isVisible());await click('control-settings-back');check('拒绝悬浮后可改用通知而不请求无障碍',await action('enable-notifications').isVisible()&&!(await state()).permission);
  await click('enable-notifications');await click('notifications-allow');check('通知允许后才继续准备',(await state()).notificationsAllowed&&(await state()).screen==='desktop'&&!(await state()).overlayAllowed);
  await click('manual-cancel');check('取消已授权但未开始的通知任务释放会话',!(await state()).projection);
  await begin('manual-interrupt');await scroll(310);await page.getByRole('heading',{name:'长图',exact:true}).waitFor();await shot('manual-17-interrupted');
  check('系统中断保留有效内容并说明已保留数量',await page.locator('.ly-result-notice').textContent().then(t=>t.includes('截图已中断')&&t.includes('2 屏'))&&!(await state()).projection);
  await begin();await scroll(310);const saved=await page.evaluate(()=>window.openai.widgetState);
  await page.reload();await page.evaluate(v=>window.dispatchEvent(new CustomEvent('openai:set_globals',{detail:{globals:{widgetState:v}}})),saved);
  check('重新挂载不恢复授权，保留可靠草稿及中断说明',await action('save').count()===1&&await page.locator('.ly-result-notice').count()===1&&await page.locator('.ly-projection-indicator').count()===0);
  for(const width of [320,390,736]){
    await page.setViewportSize({width,height:950});await prepare();
    check(width+'px 准备提示和按钮均在屏内',await inside());
    await action('capture').focus();await page.keyboard.press('Enter');await phase('recording');
    check(width+'px 键盘开始后可继续操作结束',await action('stop').evaluate(e=>e===document.activeElement));
    check(width+'px 首次教学与触控目标可用',await inside()&&await action('stop').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44;}));
    if(width===320){await shot('manual-18-first-320');const phone=await page.locator('.ly-phone').boundingBox(),button=await action('stop').boundingBox();
      await page.mouse.move(button.x+25,button.y+25);await page.mouse.down();await page.mouse.move(phone.x+26,phone.y+610,{steps:10});await page.mouse.up();await page.waitForTimeout(50);
      check('窄屏浮球移到左下时路线移至右侧且不越界',await inside()&&await page.locator('.ly-swipe-guide.right').count()===1);await shot('manual-19-drag-320');}
    const metrics=await page.locator('.ly-phone').evaluate(e=>({phone:e.clientWidth,scroll:e.scrollWidth}));layouts.push({width,...metrics});check(width+'px 手动界面无横向溢出',metrics.scroll<=metrics.phone);
    await scroll(310);await end();check(width+'px 共同结果无横向溢出',await page.locator('.ly-phone').evaluate(e=>e.scrollWidth<=e.clientWidth));
    if(width===320)await shot('manual-08-result-320');
  }
  await page.setViewportSize({width:736,height:950});await page.emulateMedia({colorScheme:'dark'});await prepare();await shot('manual-20-ready-dark');await click('capture');await phase('recording');await shot('manual-21-first-dark');
  check('深色首屏教学和结束都清晰可用',await inside()&&await action('stop').isVisible());await scroll(310);await scroll(980);await shot('manual-22-gap-dark');check('深色错误提示可见且在屏内',await inside()&&await page.locator('.ly-float-tip.error').isVisible());await end();
  await scenario('first');await click('start');await shot('manual-09-entry-dark');check('深色自动准备仍有两种路径',await action('manual').isVisible()&&await action('to-system').isVisible());
  check('浏览器无 JavaScript 异常',errors.length===0);
  await writeFile(new URL('manual-verification.json',review),JSON.stringify({version:5,checkedAt:new Date().toISOString(),checks,errors,layouts,scope:'Manual floating/notification UX simulation; no Android capture or image matching executed'},null,2));
  const items=[['manual-10-ready','01 · 找到起点再开始'],['manual-04-capturing','02 · 起点与松手位置'],['manual-11-progress','03 · 文字收起，路线保留'],['manual-12-gap-live','04 · 缺口立即反馈'],['manual-05-result','05 · 结束后检查长图'],['manual-06-help','06 · 按需查看帮助']];
  const panels=await Promise.all(items.map(async([file,title])=>'<section><h2>'+title+'</h2><img src="data:image/png;base64,'+(await readFile(new URL(file+'.png',review))).toString('base64')+'" alt="'+title+'"></section>'));
  const board=await browser.newPage({viewport:{width:1290,height:1760},deviceScaleFactor:1});
  await board.setContent('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#F7F4EE;color:#252B2A;font-family:"Microsoft YaHei",system-ui}.board{width:1290px;padding:34px}.head{display:flex;align-items:baseline;justify-content:space-between;margin-bottom:20px}h1{margin:0;font-size:29px;letter-spacing:2px}.head p{font-size:16px;margin:0;color:#646C67}.grid{display:grid;grid-template-columns:repeat(3,390px);gap:22px 26px}h2{font-size:16px;font-weight:500;margin:0 0 11px;color:#646C67}img{display:block;width:390px;height:748px;object-fit:contain}</style><div class="board"><div class="head"><h1>连页 · 手动长截图</h1><p>点开始 / 自己滑动 / 点结束</p></div><div class="grid">'+panels.join('')+'</div></div></html>');
  await board.locator('img').last().waitFor();await board.locator('.board').screenshot({path:fileURLToPath(new URL('manual-overview.png',review))});await board.close();
  console.log(checks.length+' manual checks passed; '+errors.length+' JS errors; manual-overview.png created');
}finally{await browser.close();}
