import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const runtime=process.env.LY_NODE_RUNTIME||'C:/Users/wgx/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const require=createRequire(runtime+'package.json'),{chromium}=require('playwright');
const dir=new URL('./',import.meta.url),review=new URL('review/',dir),H=require(fileURLToPath(new URL('device-help.cjs',dir)));
const browser=await chromium.launch({headless:true,executablePath:process.env.LY_CHROME||'C:/Users/wgx/.cache/puppeteer/chrome/win64-151.0.7922.71/chrome-win64/chrome.exe'});
const context=await browser.newContext({viewport:{width:736,height:950},deviceScaleFactor:1});
await context.addInitScript({path:runtime+'lucide/dist/umd/lucide.min.js'});
await context.addInitScript(()=>{window.openai={widgetState:null,setWidgetState:async value=>{window.openai.widgetState=value;setTimeout(()=>window.dispatchEvent(new CustomEvent('openai:set_globals',{detail:{globals:{widgetState:value}}})),25);}};});
const page=await context.newPage(),errors=[],checks=[],layouts=[];page.setDefaultTimeout(8000);
page.on('pageerror',e=>errors.push(e.message));await mkdir(review,{recursive:true});
const check=(name,condition=true)=>{assert.ok(condition,name);checks.push(name);};
const action=a=>page.locator(`#ly-interaction-prototype [data-action="${a}"]:visible`);
const click=async a=>action(a).first().click();
const scenario=async value=>page.locator('#ly-scenario').selectOption(value);
const shot=async name=>page.locator('.ly-phone').screenshot({path:fileURLToPath(new URL(name+'.png',review))});
const state=()=>page.evaluate(()=>window.openai.widgetState.privateContent.experience);
const offset=()=>page.locator('.ly-preview-space .ly-preview-source').evaluate(e=>parseFloat(e.style.top));
const adjust=async()=>{await page.locator('[data-corner="tl"]').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');};
const capture=async(early=false)=>{await click('start');await click('open-browser');await click('capture');if(early)await click('stop');await page.getByRole('heading',{name:'长图',exact:true}).waitFor();};
try{
  await page.goto(pathToFileURL(fileURLToPath(new URL('../../../../build/lianye-prototype/preview.html',dir))).href);
  await scenario('first');
  await action('start').waitFor();await shot('01-home');
  check('首页只留一个主任务和明确帮助',await action('start').count()===1&&await action('settings').textContent()==='帮助');
  await click('start');await page.waitForTimeout(60);await shot('02-prepare');
  check('状态回传不关闭正在操作的弹层',await page.getByRole('dialog').count()===1);
  check('首次准备默认本机路径',await page.locator('.ly-device-path').textContent().then(t=>t.includes(H.get('xiaomi').short)));
  await click('to-system');await page.locator('#ly-system-enable').click();await click('system-deny');
  check('拒绝后仍未准备好且未自动截图',!(await state()).permission&&(await state()).screen==='home');
  await click('start');await click('to-system');await page.locator('#ly-system-enable').click();await click('system-allow');
  check('授权后仍等用户从系统返回',await action('system-back').count()===1);
  await click('system-back');await shot('03-desktop');
  check('返回后直接延续任务，不再点击去截图',await action('open-browser').count()===1&&(await state()).screen==='desktop');
  await click('open-browser');await shot('04-target');await click('capture');await shot('05-capturing');
  check('截取进度和结束合在一个按钮',await page.locator('.ly-bubble').textContent().then(t=>t.includes('1 屏')&&t.includes('结束'))&&await page.locator('.ly-capture-label').count()===0);
  await page.getByRole('heading',{name:'长图',exact:true}).waitFor();await shot('06-result');
  check('自动完成保留四屏', (await state()).draft.frames===4);
  check('结果只留裁剪保存分享，没有遮盖完成和常驻撤销',await action('crop').count()===1&&await action('save').count()===1&&await action('share').count()===1&&await action('mask').count()===0&&await action('done').count()===0&&await action('undo').count()===0);
  await click('view');await click('bottom');check('查看入口可定位底部',await page.locator('.ly-result-scroll').evaluate(e=>e.scrollTop>0));
  await click('view');await click('top');await click('view');await click('zoom-in');check('放大改变实际图片尺寸',await page.locator('.ly-preview-space').evaluate(e=>e.clientWidth>400));await click('view');await click('fit');
  await click('crop');await shot('07-crop');check('裁剪默认适合宽度且内容可滚动',await page.locator('.ly-edit-image').evaluate(e=>e.clientWidth>250)&&await page.locator('.ly-editor-stage').evaluate(e=>e.scrollHeight>e.clientHeight));
  check('裁剪没有百分比滑条',await page.locator('input[type="range"]').count()===0);
  await click('crop-zoom');check('仍可看全图以定位边界',await page.locator('.ly-edit-image').evaluate(e=>e.clientWidth<150));await shot('07b-crop-overview');await click('crop-zoom');
  await adjust();check('多次方向键可调整同一裁剪角',await page.locator('[data-corner="tl"]').evaluate(e=>e===document.activeElement));
  await click('crop-undo');await click('crop-redo');await click('cancel-edit');check('取消不提交临时裁剪与撤销记录',(await state()).draft.history.length===1&&await offset()===0);
  await click('crop');await adjust();await click('apply-edit');check('应用裁剪改变源图偏移',await offset()<0);
  await click('share');await shot('09-share');await click('close-sheet');check('取消分享不标记已保存',!(await state()).draft.saved);
  await click('share');await click('share-to');check('分享交接不自动写相册，也不弹二次确认',!(await state()).draft.saved&&(await state()).draft.shared&&await page.getByRole('dialog').count()===0);
  await click('save');check('保存进度留在按钮和当前页',await action('save').isDisabled()&&await page.getByRole('dialog').count()===0);await page.waitForTimeout(850);await shot('11-saved');
  check('成功只更新状态并避免重复保存',(await state()).draft.saved&&await action('save').isDisabled()&&await page.getByRole('dialog').count()===0);
  await click('crop');await adjust();await click('apply-edit');check('再编辑恢复未保存状态',!(await state()).draft.saved);
  await click('crop');await click('crop-undo');await click('apply-edit');check('恢复保存过的裁剪版本重新认定已保存',(await state()).draft.saved);
  await click('crop');await adjust();await click('apply-edit');await click('draft-home');await shot('12-draft');
  check('普通返回保留草稿无需询问',await action('resume').count()===1&&await page.getByRole('dialog').count()===0);
  check('草稿用真实内容缩略图',await page.locator('.ly-draft-thumb .ly-article').count()===1);
  const saved=await page.evaluate(()=>window.openai.widgetState);check('持久状态小于16KiB',JSON.stringify(saved).length<16384);
  await page.reload();await page.evaluate(v=>window.dispatchEvent(new CustomEvent('openai:set_globals',{detail:{globals:{widgetState:v}}})),saved);
  await click('resume');check('重挂载恢复裁剪与历史',await offset()<0&&(await state()).draft.history.length>1);await click('draft-home');
  await click('new');await shot('10-protect');check('仅覆盖未保存草稿时保护',await action('save-new').count()===1&&await action('discard-new').count()===1);
  await click('save-new');await page.waitForTimeout(850);check('保存并新建直接继续下一任务',await action('open-browser').count()===1&&await page.getByRole('dialog').count()===0&&!(await state()).draft);
  await scenario('savefail');await click('resume');await click('save');await page.waitForTimeout(850);await shot('13-save-error');
  check('保存失败内联告知，保留结果和重试',(await state()).draft&&!await action('save').isDisabled()&&await action('save').textContent()==='重试'&&await page.getByRole('dialog').count()===0);
  await click('save');await page.waitForTimeout(850);check('失败后重试成功',(await state()).draft.saved);
  await scenario('interrupt');await capture();await shot('14-interrupted');check('中断保留两屏有效内容',(await state()).draft.frames===2&&await page.locator('.ly-result-notice').count()===1);
  await scenario('ready');await capture(true);check('主动结束保留第一屏',(await state()).draft.frames===1);
  await scenario('android10');await click('start');await click('to-system');await page.locator('#ly-system-enable').click();await click('system-allow');await click('system-back');
  check('旧安卓仅按能力请求屏幕捕获授权',await action('projection-allow').count()===1);await click('projection-deny');check('拒绝屏幕捕获不启动任务',(await state()).screen==='home'&&!(await state()).projection);
  await click('start');await click('projection-allow');await click('open-browser');await click('capture');await click('stop');await click('draft-home');await click('new');await click('discard-new');
  check('有效捕获授权没有在结束时盲目清除',await action('open-browser').count()===1&&(await state()).projection);
  await scenario('draft');await click('settings');await page.locator('#ly-bubble-toggle').uncheck();check('隐藏与停用服务分离',(await state()).permission&&!(await state()).bubble);
  await click('disable');check('停用直接生效且草稿保留',!(await state()).permission&&(await state()).draft&&await page.getByRole('dialog').count()===0);await click('home');check('服务停用仍可继续检查草稿',await action('resume').count()===1);
  for(const vendor of Object.keys(H.devices)){
    await scenario('first');await page.locator('#ly-vendor').selectOption(vendor);await click('start');
    check(`${vendor} 首次指引按本机显示`,await page.locator('.ly-device-path').textContent().then(t=>t.includes(H.get(vendor).short)));
    check(`${vendor} 产品内不要求再选择手机`,await page.locator('.ly-phone select').count()===0);await shot('oem-'+vendor);await click('restricted');
    await page.locator('.ly-details summary').click();check(`${vendor} 完整路径可按需展开`,await page.locator('.ly-details').textContent().then(t=>t.includes(H.get(vendor).full)));await click('close-sheet');
    await click('settings');await click('help');check(`${vendor} 高级排障默认折叠`,!(await page.locator('.ly-advanced').evaluate(e=>e.open)));
  }
  await shot('19-help');check('三步帮助包括手动结束和检查结果',await page.locator('.ly-steps').textContent().then(t=>t.includes('结束')&&t.includes('检查长图')));await page.locator('.ly-advanced summary').click();check('应用信息电池和ADB均保留',await action('app-info').count()===1&&await action('battery').count()===1&&await action('adb').count()===1);
  await click('app-info');await page.locator('summary').click();await click('allow-restricted');check('受限设置提供具体应用信息入口',await action('help-system').count()===1);await click('help');await page.locator('.ly-advanced summary').click();await click('battery');check('后台设置入口存在',await page.getByRole('heading',{name:'电池设置'}).count()===1);await click('help');await page.locator('.ly-advanced summary').click();await click('adb');check('高级排障保留既有包名命令',await page.locator('.ly-command').textContent().then(t=>t.includes('org.scrollloom')));await click('copy-adb');check('ADB复制交互保留且明确为模拟',await action('copy-adb').textContent()==='已复制'&&await page.locator('#ly-announcement').textContent().then(t=>t.includes('模拟')));await click('close-sheet');
  await scenario('draft');await click('resume');await click('crop');const handle=await page.locator('[data-corner="tl"]').boundingBox();
  await page.mouse.move(handle.x+22,handle.y+22);await page.mouse.down();await page.mouse.move(handle.x+30,handle.y+52,{steps:6});await page.mouse.up();await click('apply-edit');check('实际拖动手柄可裁剪',await offset()<0);
  await scenario('ready');await click('start');await click('open-browser');const bubble=await page.locator('.ly-bubble').boundingBox();
  await page.mouse.move(bubble.x+30,bubble.y+25);await page.mouse.down();await page.mouse.move(bubble.x-170,bubble.y+95,{steps:6});await page.mouse.up();check('拖动按钮不会误截取',(await state()).screen==='target');check('侧边按钮可移动',await page.locator('.ly-bubble').evaluate(e=>parseFloat(e.style.top)>245));
  await scenario('first');await click('start');for(let i=0;i<5;i++)await page.keyboard.press('Tab');check('弹层键盘焦点保持内部',await page.evaluate(()=>!!document.activeElement.closest('[role="dialog"]')));await page.keyboard.press('Escape');check('关闭后焦点返回主动作',await action('start').evaluate(e=>e===document.activeElement));
  for(const width of [320,390,736]){await page.setViewportSize({width,height:950});
    for(const sc of ['first','draft','denied']){await scenario(sc);const metrics=await page.evaluate(()=>({body:document.body.scrollWidth,phone:document.querySelector('.ly-phone').scrollWidth,frame:document.querySelector('.ly-phone').clientWidth}));layouts.push({width,scenario:sc,...metrics});check(`${width}px ${sc}无横向溢出`,metrics.body<=width&&metrics.phone<=metrics.frame);}
    await scenario('draft');await click('resume');await click('crop');await adjust();check(`${width}px 裁剪控制条无溢出`,await page.locator('.ly-editor-controls').evaluate(e=>e.scrollWidth<=e.clientWidth));await click('crop-zoom');check(`${width}px 全图完整留在编辑视口`,await page.locator('.ly-edit-image').evaluate(e=>e.clientHeight<=e.parentElement.clientHeight-40));await click('cancel-edit');await click('share');check(`${width}px 分享弹层无溢出`,await page.locator('.ly-phone').evaluate(e=>e.scrollWidth<=e.clientWidth));
    if(width===320){await scenario('first');await shot('15-home-320');}
  }
  await page.setViewportSize({width:736,height:950});await page.emulateMedia({colorScheme:'dark'});await scenario('first');await shot('16-home-dark');await scenario('draft');await click('resume');await shot('17-result-dark');
  check('深色主题实际生效',await page.locator('.ly-phone').evaluate(e=>getComputedStyle(e).backgroundColor==='rgb(29, 36, 34)'));
  check('所有三个主要动作都有图标',await page.locator('.ly-result-actions svg').count()===3);
  check('浏览器无JavaScript异常',errors.length===0);
  const fragment=await readFile(new URL('lianye-interaction-prototype.html',dir),'utf8');
  check('片段小于1MB',Buffer.byteLength(fragment)<1_000_000);check('没有真实网络或系统API',! /\b(?:fetch|XMLHttpRequest|WebSocket|getDisplayMedia|share)\s*\(|navigator\./.test(fragment));check('遮盖功能和示例号码均移除',!fragment.includes('遮盖')&&!fragment.includes('138 0000')&&!fragment.includes('ly-mask'));
  await writeFile(new URL('verification.json',review),JSON.stringify({version:5,checkedAt:new Date().toISOString(),checks,errors,layouts,fragmentBytes:Buffer.byteLength(fragment),scope:'Browser prototype simulation; not Android device verification'},null,2));console.log(`${checks.length} checks passed; ${errors.length} JS errors`);
}finally{await browser.close();}
