import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const runtime=process.env.LY_NODE_RUNTIME||'C:/Users/wgx/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {chromium}=createRequire(runtime+'package.json')('playwright');
const dir=new URL('./',import.meta.url),review=new URL('review/',dir);
const browser=await chromium.launch({headless:true,executablePath:process.env.LY_CHROME||'C:/Users/wgx/.cache/puppeteer/chrome/win64-151.0.7922.71/chrome-win64/chrome.exe'});
const page=await browser.newPage({viewport:{width:736,height:1000}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
const lucide=await readFile(runtime+'lucide/dist/umd/lucide.min.js','utf8');
// The host runtime normally supplies this library. Use its installed copy for offline QA.
await page.route('https://unpkg.com/**',route=>route.fulfill({contentType:'application/javascript',body:route.request().url().includes('lucide')?lucide:''}));
try {
  await page.goto(pathToFileURL(fileURLToPath(new URL('../../../../build/lianye-prototype/host-preview.html',dir))).href);
  const ui=page.frameLocator('iframe');
  await ui.locator('#ly-scenario').selectOption('first');
  await ui.locator('[data-action="start"]').waitFor();
  await ui.locator('[data-action="start"] svg').waitFor();
  check('宿主 iframe 内主界面与图标出现',await ui.locator('.ly-logo').count()===1);
  await ui.locator('.ly-phone').screenshot({path:fileURLToPath(new URL('18-host-home.png',review))});
  await ui.locator('[data-action="start"]').click();await ui.locator('[data-action="to-system"]').waitFor();
  check('宿主环境下首个主动作生效',await ui.getByRole('dialog').count()===1);
  await ui.getByRole('button',{name:'关闭',exact:true}).click();
  await ui.locator('#ly-scenario').selectOption('ready');await ui.locator('[data-action="start"]').click();await ui.locator('[data-action="open-browser"]').click();await ui.locator('[data-action="capture"]').click();
  await ui.getByRole('heading',{name:'长图',exact:true}).waitFor({timeout:8000});
  await ui.locator('[data-action="crop"]').click();await ui.locator('[data-corner="tl"]').focus();await page.keyboard.press('ArrowDown');await ui.locator('[data-action="apply-edit"]').click();
  check('宿主环境下截取与裁剪闭环可用',await ui.locator('.ly-preview-source').evaluate(e=>parseFloat(e.style.top)<0));
  await ui.locator('[data-action="save"]').click();await page.waitForTimeout(850);
  check('宿主环境下保存不弹二次确认',await ui.getByRole('dialog').count()===0&&await ui.locator('[data-action="save"]').isDisabled());
  const frame=page.frames().find(f=>f!==page.mainFrame());
  const targets=await frame.evaluate(()=>[...document.querySelectorAll('.ly-phone button')].filter(e=>!e.disabled&&e.getClientRects().length).map(e=>({label:e.getAttribute('aria-label')||e.textContent.trim(),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));
  check('结果页操作目标至少 44×44 px',targets.every(t=>t.width>=44&&t.height>=44));
  await ui.locator('#ly-scenario').selectOption('manual');await ui.locator('[data-action="start"]').click();await ui.locator('[data-action="projection-allow"]').click();await ui.locator('[data-action="open-browser"]').click();await page.waitForTimeout(950);
  check('宿主手动等待开始，不自动滚动',await ui.locator('.ly-target-scroll').evaluate(e=>e.scrollTop===0)&&await ui.locator('.ly-manual-float [data-action="capture"]').count()===1);
  await ui.locator('[data-action="capture"]').click();await ui.getByRole('button',{name:'结束截取，已截 1 屏',exact:true}).waitFor();
  await ui.locator('.ly-target-scroll').hover();await page.mouse.wheel(0,310);await page.waitForTimeout(300);await ui.locator('[data-action="stop"]').click();await ui.getByRole('heading',{name:'长图',exact:true}).waitFor();
  check('宿主手动滑动后明确结束进入共同结果',await ui.getByRole('heading',{name:'长图',exact:true}).count()===1&&await ui.locator('.ly-preview-space').evaluate(e=>e.clientHeight>800));
  check('宿主手动完成后捕获状态消失',await ui.locator('.ly-projection-indicator').count()===0);
  check('宿主运行无 JavaScript 异常',errors.length===0);
  const lum=hex=>{const v=hex.replace('#','').match(/../g).map(p=>parseInt(p,16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2];};
  const contrast=(a,b)=>{const v=[lum(a),lum(b)].sort((x,y)=>y-x);return +( (v[0]+.05)/(v[1]+.05) ).toFixed(2);};
  const colors=[['light text','#252B2A','#F7F4EE'],['light secondary','#646C67','#F7F4EE'],['light accent text','#A54023','#F7F4EE'],['dark text','#F7F4EE','#1D2422'],['dark secondary','#ADB7B0','#1D2422'],['dark accent text','#F4A584','#1D2422']].map(([name,fg,bg])=>({name,fg,bg,ratio:contrast(fg,bg)}));
  check('浅深主题的正文与次级文字对比度达标',colors.every(c=>c.ratio>=4.5));
  const items=[['01-home','01 · 开始长截图'],['02-prepare','02 · 本机开启路径'],['05-capturing','03 · 自动截取'],['06-result','04 · 长图预览'],['07-crop','05 · 裁剪'],['11-saved','06 · 保存完成']];
  const panels=await Promise.all(items.map(async([file,title])=>`<section><h2>${title}</h2><img src="data:image/png;base64,${(await readFile(new URL(file+'.png',review))).toString('base64')}" alt="${title}"></section>`));
  const board=await browser.newPage({viewport:{width:1290,height:1760},deviceScaleFactor:1});
  await board.setContent(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#F7F4EE;color:#252B2A;font-family:"Microsoft YaHei",system-ui}.board{width:1290px;padding:34px}.head{display:flex;align-items:baseline;justify-content:space-between;margin-bottom:20px}h1{margin:0;font-size:29px;letter-spacing:2px}.head p{font-size:16px;margin:0;color:#646C67}.grid{display:grid;grid-template-columns:repeat(3,390px);gap:22px 26px}h2{font-size:16px;font-weight:500;margin:0 0 11px;color:#646C67}img{display:block;width:390px;height:748px;object-fit:contain}</style><div class="board"><div class="head"><h1>连页 · 交互原型</h1><p>自动长截图 / 本机处理</p></div><div class="grid">${panels.join('')}</div></div></html>`);
  await board.locator('img').last().waitFor();await board.locator('.board').screenshot({path:fileURLToPath(new URL('overview.png',review))});
  await board.close();
  await writeFile(new URL('host-verification.json',review),JSON.stringify({version:5,checkedAt:new Date().toISOString(),checks,errors,targets,colors,offlineRuntime:'Host Lucide supplied from installed package; optional tooltip libraries omitted'},null,2));
  console.log(`${checks.length} host checks passed; overview.png created`);
}finally{await browser.close();}
