package org.lianye.ui.common.theme

import androidx.compose.ui.graphics.Color

// Generated by tool/sync_brand_assets.py from design/tokens/tokens.json.
internal object BrandPalette {
    val Paper = Color(0xFFF7F4EE)
    val Ink = Color(0xFF252B2A)
    val Accent = Color(0xFFDB653D)
    val DarkBackground = Color(0xFF1D2422)
    val DarkAccent = Color(0xFFF4A584)
}
